version: "3.9"  # optional since v1.27.0
services:
  btp-front:
    build: btp-front
    ports:
      - "80:80"
    links:
      - btp-php
    volumes:
        - ./logs/nginx:/var/log/nginx
  btp-php:
    build: btp-php
    links:
      - btpd
  btpd:
    platform: linux/amd64
    build: btpd
    platform: linux/amd64
    ports:
      - "37000:37000"
      - "37001:37001"
      - "37002:37002"
      - "37003:37003"
      - "37004:37004"
      - "38001:38001"
      - "38001:38001/udp"
    volumes:
      - ./logs/btpd:/logs
      - ./storage:/storage